name = "Q"
license = "MIT"
licenselink = "https://github.com/yourusername/Q/blob/master/LICENSE"
description = "A minimal Hugo theme using Tailwind CSS"
homepage = "https://github.com/yourusername/Q"
tags = ["blog", "minimal", "responsive", "light", "dark"]
features = ["blog", "responsive", "dark mode"]
min_version = "0.80.0"

[author]
  name = "Your Name"
  homepage = "https://yourwebsite.com"